# Generated by Django 5.0.6 on 2024-07-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficpredictionresult',
            name='image_link',
        ),
        migrations.AddField(
            model_name='trafficpredictionresult',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='results/', verbose_name='图片'),
        ),
    ]
