# Generated by Django 5.0.6 on 2024-07-07 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_remove_road_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='connected_to',
        ),
    ]
