# Generated by Django 5.0.6 on 2024-07-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_road_prediction_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprediction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
