# Generated by Django 5.0.6 on 2024-07-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_alter_historicalprediction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprediction',
            name='user',
        ),
    ]
