# Generated by Django 5.0.6 on 2024-07-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_remove_historicalprediction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='road',
            name='longitude',
        ),
        migrations.AddField(
            model_name='road',
            name='green_light',
            field=models.IntegerField(default=0, verbose_name='绿灯时间'),
        ),
        migrations.AddField(
            model_name='road',
            name='red_light',
            field=models.IntegerField(default=0, verbose_name='红灯时间'),
        ),
    ]
