# Generated by Django 5.0.6 on 2024-07-10 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_remove_road_latitude_remove_road_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='交叉口id')),
                ('type', models.CharField(choices=[('cross', 'Crossroad'), ('t_junction', 'T-junction')], max_length=10)),
                ('current_red_time', models.IntegerField(default=0, verbose_name='当前红灯时间')),
                ('current_green_time', models.IntegerField(default=0, verbose_name='当前绿灯时间')),
                ('longitude', models.FloatField(default=0.0, verbose_name='经度')),
                ('latitude', models.FloatField(default=0.0, verbose_name='纬度')),
            ],
            options={
                'verbose_name': '交叉口信息',
                'verbose_name_plural': '交叉口信息',
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='historicalprediction',
            name='road',
        ),
        migrations.RemoveField(
            model_name='trafficpredictionresult',
            name='road',
        ),
        migrations.RemoveField(
            model_name='road',
            name='green_light',
        ),
        migrations.RemoveField(
            model_name='road',
            name='prediction_image1',
        ),
        migrations.RemoveField(
            model_name='road',
            name='prediction_image2',
        ),
        migrations.RemoveField(
            model_name='road',
            name='red_light',
        ),
        migrations.AddField(
            model_name='road',
            name='dataset_link',
            field=models.URLField(default='', verbose_name='数据集链接'),
        ),
        migrations.AddField(
            model_name='road',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='road',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='road',
            name='main_road',
            field=models.IntegerField(default=0, verbose_name='所属大道'),
        ),
        migrations.CreateModel(
            name='RoadIntersectionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.intersection', verbose_name='交叉口id')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.road', verbose_name='道路id')),
            ],
            options={
                'verbose_name': '道路交叉口关系信息',
                'verbose_name_plural': '道路交叉口关系信息',
            },
        ),
        migrations.CreateModel(
            name='TrafficPrediction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='查询记录id')),
                ('data1', models.FloatField(default=0.0)),
                ('data2', models.FloatField(default=0.0)),
                ('data3', models.FloatField(default=0.0)),
                ('data4', models.FloatField(default=0.0)),
                ('data5', models.FloatField(default=0.0)),
                ('data6', models.FloatField(default=0.0)),
                ('data7', models.FloatField(default=0.0)),
                ('data8', models.FloatField(default=0.0)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.road', verbose_name='道路id')),
            ],
            options={
                'verbose_name': '车流量预测图表',
                'verbose_name_plural': '车流量预测图表',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='HistoricalPrediction',
        ),
        migrations.DeleteModel(
            name='TrafficPredictionResult',
        ),
    ]
