# Generated by Django 5.0.6 on 2024-07-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_alter_intersection_options_alter_road_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadtraffic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
