# Generated by Django 5.0.6 on 2024-07-11 15:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_alter_roadtraffic_lane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intersection',
            name='current_green_time',
        ),
        migrations.AddField(
            model_name='intersection',
            name='current_green_time_1',
            field=models.IntegerField(default=0, verbose_name='当前绿灯时间1'),
        ),
        migrations.AddField(
            model_name='intersection',
            name='current_green_time_2',
            field=models.IntegerField(default=0, verbose_name='当前绿灯时间2'),
        ),
        migrations.CreateModel(
            name='TrafficLightPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('red_light_result', models.IntegerField(default=0, verbose_name='红灯结果')),
                ('green_light_result1', models.IntegerField(default=0, verbose_name='绿灯结果1')),
                ('green_light_result2', models.IntegerField(default=0, verbose_name='绿灯结果2')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.road', verbose_name='道路id')),
            ],
            options={
                'verbose_name': '历史结果预测',
                'verbose_name_plural': '历史结果预测',
            },
        ),
    ]
