# Generated by Django 5.0.6 on 2024-07-11 16:44

import car.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_remove_intersection_current_green_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlightprediction',
            name='timestamp',
            field=models.TimeField(default=car.models.now_time, verbose_name='时间'),
        ),
    ]
