# Generated by Django 5.0.6 on 2024-07-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_alter_trafficlightprediction_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intersection',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='intersection',
            old_name='longitude',
            new_name='lng',
        ),
        migrations.RenameField(
            model_name='road',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='road',
            old_name='longitude',
            new_name='lng',
        ),
    ]
