# Generated by Django 5.0.6 on 2024-07-11 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_rename_latitude_intersection_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlightprediction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
    ]
