# Generated by Django 5.0.6 on 2024-07-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0018_remove_road_dataset_link_road_current_green_time_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficprediction',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='时间'),
        ),
    ]
