# Generated by Django 5.0.6 on 2024-07-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0020_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntersectionRelationshipQWE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id0_relations', to='car.intersection')),
                ('id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id1_relations', to='car.intersection')),
                ('id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id2_relations', to='car.intersection')),
                ('road1', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road1', to='car.road')),
                ('road2', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road2', to='car.road')),
                ('road3', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road3', to='car.road')),
            ],
            options={
                'verbose_name': '交叉口关系',
                'verbose_name_plural': '交叉口关系',
            },
        ),
        migrations.DeleteModel(
            name='IntersectionRelationship',
        ),
    ]
