# Generated by Django 5.0.6 on 2024-07-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUsers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(help_text='邮箱', max_length=40, verbose_name='邮箱'),
        ),
    ]
