# Generated by Django 5.0.6 on 2024-07-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUsers', '0002_remove_users_first_name_remove_users_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
