# Generated by Django 5.0.6 on 2024-07-09 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUsers', '0003_users_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=4)),
                ('expire_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
